name: "resolver"
services:
  resolver:
    image: "11notes/bind:9.18.31"
    container_name: "resolver"
    command: ["resolver"]
    environment:
      TZ: "Europe/Zurich"
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "8053:8053/tcp"
    sysctls:
      - "net.ipv4.ip_unprivileged_port_start=53"
    restart: always