services:
  bind:
    image: "11notes/bind:9.18.30"
    container_name: "bind"
    environment:
      TZ: "Europe/Zurich"
    volumes:
      - "etc:/bind/etc"
      - "var:/bind/var"
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "8053:8053/tcp"
    sysctls:
      - "net.ipv4.ip_unprivileged_port_start=53"
    restart: always
volumes:
  etc:
  var: