name: cron

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: write

    steps:
      - name: checkout all tags
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
        with:
          ref: 'master'
          fetch-depth: 0

      - name: get latest version
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            (async()=>{
              let found = false;
              const res = await fetch('https://www.isc.org/download/');
              if(res && res.status === 200){
                const html = await res.text();
                const td = [...html.replace(/[\r\n]*/ig, '').matchAll(/<td[^>]*>(.*?)<\/td>/ig)];
                for(let i=0; i<td.length; i++){
                  if(/This software is recommended for production use/i.test(td[i][0]) && td[i+1]?.input && /Current Stable/i.test(td[i+1][0]) && td[i+2]?.input && /downloads\.isc\.org\/isc\/bind9/i.test(td[i+2][0]) && /download-version-text/i.test(td[i][1])){
                    const div = [...td[i][1].matchAll(/<div[^>]*>(.*?)<\/div>/ig)];
                    if(div.length >= 1){
                      core.exportVariable('LATEST_VERSION', div[0][1]);
                      core.info(`found bind version ${div[0][1]}`);
                      found = true;
                      break;
                    }
                  }
                }
              }

              if(!found){
                core.exportVariable('LATEST_VERSION', 'null');
              }
            })();

      - name: get last tag
        run: |
          export LATEST_TAG=$(git describe --abbrev=0 --tags `git rev-list --tags --max-count=1` | sed 's|v||')
          echo "WORKFLOW_UPDATE_BASE64JSON=$(echo '{"version":"'${LATEST_VERSION}'", "tag":"'${LATEST_TAG}'", "unraid":true, "nobody":true}' | base64 -w 0)" >> "${GITHUB_ENV}"

      - name: call org.update
        uses: the-actions-org/workflow-dispatch@3133c5d135c7dbe4be4f9793872b6ef331b53bc7
        if: env.LATEST_VERSION != 'null' && env.LATEST_VERSION != ''
        with:
          wait-for-completion: false
          workflow: org.update.yml
          token: "${{ secrets.REPOSITORY_TOKEN }}"
          inputs: '{ "etc":"${{ env.WORKFLOW_UPDATE_BASE64JSON }}" }'